### ISSUE TITLE
Facebookページの運用方法

### ISSUE THREAD

**Issue by naotoando** [galleriejp/tasks#17]
投稿回数はほどほどに
投稿はたくさん送ればいいわけではないということが統計的にわかっています。
送れば送るほど反応が鈍くなり、「飽き」が発生します。

つまり、ウザいと思われるということです。 一日一回か、二回程度がいいでしょう。
下記調査によると週５～７回程度が良いという統計が出ています。

**Comment by naotoando** [comment]
一番まとまっているサイト
http://syn3.info/sc/facebook/170.html

**Comment by aokirina** [comment]
まあまあコンテンツ力がきちんと高くて、広告頼りじゃないfacebookページが
一定のいいね数獲得するために使った広告費とか、目安になる情報落ちてないかな〜＞＜？

**Comment by aokirina** [comment]
一番安くて600円×7日間＝4,200円かかる
