### ISSUE TITLE
動画カテゴリ（仮）

### ISSUE THREAD

**Issue by naotoando** [galleriejp/tasks#18]
# 化粧品の紹介

流行り
発色気になる
◯◯メイク的なやつの紹介
# ネイルの塗り方

塗り方
「バレンタインネイル」などテーマ縛りでスライドショー的な
# コーディネート

「春の先取り」的なテーマでスライドショー。各服に矢印で名称やブランド、値段など入れたい。
プレプロでやり方探る
# お店・フード紹介

お店やフード紹介したいマンと仲良くなる。
instagramでフードの動画投稿されていないか探ったところ、ほぼない。
# メイクパーツ

目だけとか、唇だけとか。
頬出すやつだと顔全体必要。
# 美容師のマネキン
# ヨガインストラクター
# イベント

自分たちが実際に行くのがベスト。
その場で女の子ナンパ
# トラベル
# インテリア

iemo参考になるかも
# ニュース・トレンド

**Comment by aokirina** [comment]
動画つくるときのポイント、
①女の子がみたいと思うか
②単価や工数的に作成可能かどうか

だと思うんだけど、
あくまで①を目標におくべきで
②に頭持ってかれないように注意しようね！

insta上に動画がなくても、①のニーズがあればどうにかして動画作成する手段を探る。
どれだけ頭使って工夫するかの勝負。
ぱっと思いつくような制作方法なら他の会社もあっという間にできてしまうので！

## 

①②を考慮しているといちいち動画作成時の意思決定カロリーが高いのなら
どの程度１動画あたりに単価さけるか、みたいなところ議論したり考えたりする必要ある！
↑こういう部分、わたしが気付いてないとことか
どんどん制度化していったりできるようにしてこー！
