### ISSUE TITLE
instagram別アカウント案

### ISSUE THREAD

**Issue by naotoando** [galleriejp/tasks#4]
京都のお店とか場所、名所を撮影して動画で紹介していくアカウントを作ろうかと思った。

理由は
1.自分でもインスタのアカウントを運用すべきだと思った
2.撮影したものがgallerieの今のアカウントに溜まってる写真とそぐわない動画も出てくる可能性があるため発信場所として
3.どういった動画が好まれるか試しやすいかなって思った

議論点
・必要かどうか
・gallerieにあげて、それをリグラムでもいいと思う
・逆パターンもある

↑
南部ちゃん手伝ってくれないかなー

**Comment by aokirina** [comment]
アカウント分ける、っていう案賛成！

①具体的にどういう立ち位置のインスタアカウントを作成することを予定してる？
　京都の名所紹介アカウントなのか、
　女の子向けの飲食・観光地・スポット紹介アカウントなのか…とかとか！

②わたしが考えていた別アカ作成について
　（これは別でissue立てて話し合いましょう）
　（いまは話し合う必要ないかなと思ってます）
　けっこう後の段階の話。
　後々動画を公開していくことになるけれど
　今後撮影していく予定の動画と、今インスタに投稿している画像が
　あのアカウントに混在していくのが
　インスタのブランディング（統一感等）的に良くないと思ってる。
　--
　動画＝ある程度役に立つもの（アイキャッチが醜い可能性あり）
　現在のインスタの写真＝役に立たないがただ綺麗なもの
　--
　現在のアカウントのブランディングを守るために、
　gallerie_videoみたいな別アカウントをつくって
　役に立つ動画系はそこにアップするのどうかなー。
　現アカウントは、gallerie_videoにユーザーを誘導するためのブースター的な役割になるかなと。
　そういう背景で、別アカウント作成を検討してた！

**Comment by naotoando** [comment]
①京都の名所やお店紹介アカウントだと思ってる。
理由は②の意見も複合すると、
gallerieとしての動画となると、ターゲットに沿ったり、女の子向けというので絞られるので動画の題材に縛りができてしまう。それよりもまずは、どんな動画がうけるのか試すべきかなーって思って幅広いジャンル＆クオリティーの保障のいらないアカウントを作ってはと思った。
それならば、普通の生活の中からもスマホで動画撮って素材を集められると思い。
大学とか鴨川とかでもいいと思ってる。同じ場所でも昼夜で景色違うし。

そこから生まれる戦略として。
1.京都（関西）を動画で紹介するということによってできるかもしれない多フォロワーアカウント
2.店舗紹介時による、その店のアカウントによるリグラム
3.instagramでの店舗紹介によるコンサル
4.gallerieに親和性の高い動画の場合は、
まずgallerieのアカウントで投稿→その後京都アカウントでリグラム→gallerieのフォロワー増えればな。

とはいえ、この案はすぐにgallerieのアカウントに効果があるとは言えない。
というよりも動画の効果測定や動画測定のためってのが強い。

**Comment by aokirina** [comment]
京都の名所やお店の紹介アカウントを作る目的が
「どんな動画がうけるか」を試すためだって話やけど、
それだと、ギャラリーと親和性が薄いかなって思う！

ギャラリーのユーザーと
京都の名所アカウントのユーザーはけっこう乖離してくるかなーて。

instagramの店舗紹介コンサルとかをやるのであれば
完全に京都紹介アカウントは
キャッシュのためにやる、とか割り切らないといけないと思う！
